# Generated by Django 2.0.6 on 2018-06-18 23:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('fecha', models.CharField(blank=True, help_text='Enero 2017 - Octubre 2018', max_length=100)),
                ('texto', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Experiencia',
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('centro', models.CharField(blank=True, max_length=100)),
                ('fecha', models.CharField(blank=True, help_text='Enero 2017 - Octubre 2018', max_length=100)),
                ('texto', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Estudios',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nivel', models.PositiveIntegerField(choices=[(30, 30), (50, 50), (70, 70), (90, 90), (100, 100)])),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
                ('nivel', models.PositiveIntegerField(choices=[(30, 30), (50, 50), (70, 70), (90, 90), (100, 100)])),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(max_length=50, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=50)),
                ('lugar', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('tlf', models.CharField(blank=True, max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('intereses', models.TextField(blank=True)),
                ('apariencia', models.IntegerField(choices=[(1, 'Taylor'), (2, 'Jane'), (3, 'Williams')], default=2)),
                ('cv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.Curriculo')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.Image')),
            ],
            options={
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('img', models.ManyToManyField(to='portfolio.Image')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('github', 'GitHub'), ('google', 'Google ')], max_length=20)),
                ('enlace', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
    ]
