# Generated by Django 2.0.6 on 2018-06-18 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180618_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.Curriculo'),
        ),
    ]
